# Generated by Django 5.2 on 2025-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Animal', models.IntegerField()),
                ('Animal_Name', models.CharField(default=1, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Category', models.IntegerField()),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Client', models.IntegerField()),
                ('Client_Login', models.CharField(max_length=50)),
                ('Client_Password', models.CharField(max_length=50)),
                ('Client_Second_Name', models.CharField(max_length=100)),
                ('Client_First_Name', models.CharField(max_length=100)),
                ('Client_Third_Name', models.CharField(max_length=100)),
                ('Client_Email', models.CharField(max_length=150)),
                ('Client_Phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Manufacturer', models.IntegerField()),
                ('Manufacturer_Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Status', models.IntegerField()),
                ('Status_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Order', models.IntegerField()),
                ('Client_ID', models.IntegerField()),
                ('Status_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Product', models.IntegerField()),
                ('Product_Image', models.ImageField(upload_to='images/')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Manufacturer_ID', models.IntegerField()),
                ('Animal_ID', models.IntegerField(default=1)),
                ('Category_ID', models.IntegerField(default=1)),
                ('Product_Info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.IntegerField()),
                ('Product_ID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField()),
                ('Product_ID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Cart_Buy_Check', models.BooleanField(default=True)),
            ],
        ),
    ]
