# Generated by Django 5.2 on 2025-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='Animal_Name',
            field=models.CharField(max_length=30),
        ),
    ]
