# Generated by Django 5.2 on 2025-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_animals_animal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manufacturers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_statuses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='animals',
            name='ID_Animal',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='ID_Category',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='ID_Client',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='ID_Manufacturer',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_statuses',
            name='ID_Status',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ID_Order',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='ID_Product',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
