# Generated by Django 5.2 on 2025-05-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_animals_id_remove_categories_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.clients'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Client_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.clients'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Status_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.order_statuses'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Animal_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.animals'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Category_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Manufacturer_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.manufacturers'),
        ),
        migrations.AlterField(
            model_name='productsinorders',
            name='Order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.orders'),
        ),
        migrations.AlterField(
            model_name='productsinorders',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.products'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.products'),
        ),
    ]
