# Generated by Django 5.2 on 2025-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_shoppingcart_user_id_shoppingcart_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='ID_Animal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='ID_Category',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='ID_Client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturers',
            name='ID_Manufacturer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_statuses',
            name='ID_Status',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ID_Order',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='ID_Product',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
