# Generated by Django 5.2 on 2025-05-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_animals_id_animal_alter_categories_id_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Category_ID',
        ),
    ]
