# Generated by Django 5.2 on 2025-05-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_products_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.categories'),
        ),
    ]
