# Generated by Django 5.2 on 2025-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_products_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Price',
            field=models.IntegerField(default=0),
        ),
    ]
